### ISSUE TITLE
repeat previously defined assignments

### ISSUE THREAD

**Issue by mattdzugan** [skirmer/radlibs#3]
It would be neat to be able to have a specific word choice be referenced multiple times within the radlib.  You see this every once in a while in the pencil paper versions.

An example use case would be in re-imagining the phrase

> How much wood could a woodchuck chuck if a woodchuck could chuck wood?

# Currently
Currently you might do something like
`How much _noun_ could a _noun_ _verb_ if a _noun_ could _verb_ _noun_?`

whereas that will give something like
>How much *apple* could a *banana*  *catch* if a *dog* could *eat* *fish*?

# Proposal
having someway to refer to previously assigned words might be fun.
something like:
`How much _noun1_ could a _noun2_ _verb1_ if a _noun2_ could _verb1_ _noun1_?`

whereas that will give something like
>How much *apple* could a *banana*  *catch* if a *banana* could *catch* *apple*?

**Comment by skirmer** [comment]
I like this idea- I’ll see if I can whip something up quickly. Or, PRs welcome if you feel like writing it! :)

**Comment by skirmer** [comment]
Resolved with #4
